# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {
    blacklistedKernelModules = ["ideapad-laptop"];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    initrd = {
      availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
      luks.devices = [
        {
          name = "root";
          device = "/dev/sda2";
          preLVM = true;
          allowDiscards = true;
        }
      ];
    };
  };

  hardware = {
    cpu.intel.updateMicrocode = true;
    bluetooth.enable = false;
    opengl.extraPackages = [ pkgs.vaapiIntel ];
    pulseaudio = {
      enable = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/09ccf840-230c-4d40-ace3-36de967dbc21";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/63F8-1A74";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bb3ed0ea-2bac-4f32-bb82-a5a0679140f3"; }
    ];

  nix.maxJobs = lib.mkDefault 4;

  services.kmscon.enable = true;
  powerManagement.enable = true;
  #powerManagement.cpuFreqGovernor = "powersave";
}
